############################################################
#
# web访问端口号
#
############################################################
server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.235.100:3306/newmall?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    password: Centerm123!@#