############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newmall?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    password: zwq123!@#
  redis:
    database: 0
    host: 192.168.235.31
    port: 6379
    password: 123456
# Redis 哨兵模式
#    database: 0
#    password:  123456
#    sentinel:
#      master: mymaster
#      nodes: 192.168.235.31:26379,192.168.235.32:26379,192.168.235.33:26379
# Redis 集群模式
#    password:  123456
#    cluster:
#      nodes: 192.168.1.201:6379,192.168.1.202:6379,192.168.1.203:6379,192.168.1.204:6379,192.168.1.205:6379,192.168.1.206:6379